# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: 
  password: 

development:
  <<: *default
  database: customer_feedback_development

test:
  <<: *default
  database: customer_feedback_test

# production:
#   adapter: sqlite3
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
